import { Language, Lesson, Voucher, ExchangeRate } from './types';

export const languages: Language[] = [
  {
    id: 'banjar',
    name: 'Bahasa Banjar',
    region: 'Kalimantan Selatan',
    flag: '🏝️',
    description: 'Bahasa daerah yang digunakan oleh suku Banjar di Kalimantan Selatan. Pelajari cara berkomunikasi dengan penduduk lokal dalam kehidupan sehari-hari.',
    totalLessons: 12,
    totalExp: 1200,
    difficulty: 'beginner',
  },
  {
    id: 'jawa',
    name: 'Bahasa Jawa',
    region: 'Jawa Tengah & Timur',
    flag: '🏛️',
    description: 'Bahasa daerah dengan penutur terbanyak di Indonesia. Pelajari unggah-ungguh dan komunikasi sehari-hari.',
    totalLessons: 15,
    totalExp: 1500,
    difficulty: 'beginner',
    comingSoon: true,
  },
  {
    id: 'sunda',
    name: 'Bahasa Sunda',
    region: 'Jawa Barat',
    flag: '🌄',
    description: 'Bahasa daerah masyarakat Sunda yang kaya akan kesantunan dan keindahan.',
    totalLessons: 12,
    totalExp: 1200,
    difficulty: 'beginner',
    comingSoon: true,
  },
  {
    id: 'minang',
    name: 'Bahasa Minangkabau',
    region: 'Sumatera Barat',
    flag: '🏔️',
    description: 'Bahasa daerah Minangkabau yang dikenal dengan pepatah dan peribahasa indahnya.',
    totalLessons: 10,
    totalExp: 1000,
    difficulty: 'beginner',
    comingSoon: true,
  },
  {
    id: 'bali',
    name: 'Bahasa Bali',
    region: 'Bali',
    flag: '🌺',
    description: 'Bahasa daerah Pulau Dewata dengan tingkatan bahasa yang unik.',
    totalLessons: 12,
    totalExp: 1200,
    difficulty: 'intermediate',
    comingSoon: true,
  },
  {
    id: 'bugis',
    name: 'Bahasa Bugis',
    region: 'Sulawesi Selatan',
    flag: '⛵',
    description: 'Bahasa suku Bugis yang terkenal dengan tradisi maritim dan aksara Lontara.',
    totalLessons: 10,
    totalExp: 1000,
    difficulty: 'intermediate',
    comingSoon: true,
  },
  {
    id: 'batak',
    name: 'Bahasa Batak Toba',
    region: 'Sumatera Utara',
    flag: '⛰️',
    description: 'Bahasa suku Batak Toba di sekitar Danau Toba yang khas dan ekspresif.',
    totalLessons: 12,
    totalExp: 1200,
    difficulty: 'intermediate',
    comingSoon: true,
  },
  {
    id: 'aceh',
    name: 'Bahasa Aceh',
    region: 'Aceh',
    flag: '🌙',
    description: 'Bahasa masyarakat Aceh dengan pengaruh budaya Islam yang kuat.',
    totalLessons: 10,
    totalExp: 1000,
    difficulty: 'intermediate',
    comingSoon: true,
  },
  {
    id: 'dayak',
    name: 'Bahasa Dayak Ngaju',
    region: 'Kalimantan Tengah',
    flag: '🌳',
    description: 'Bahasa suku Dayak Ngaju di pedalaman Kalimantan.',
    totalLessons: 10,
    totalExp: 1000,
    difficulty: 'intermediate',
    comingSoon: true,
  },
  {
    id: 'ambon',
    name: 'Bahasa Ambon',
    region: 'Maluku',
    flag: '🌊',
    description: 'Bahasa Melayu Ambon yang digunakan di kepulauan Maluku.',
    totalLessons: 10,
    totalExp: 1000,
    difficulty: 'beginner',
    comingSoon: true,
  },
  {
    id: 'papua',
    name: 'Bahasa Papua (Biak)',
    region: 'Papua',
    flag: '🦜',
    description: 'Salah satu bahasa Papua yang digunakan di Teluk Cenderawasih.',
    totalLessons: 8,
    totalExp: 800,
    difficulty: 'advanced',
    comingSoon: true,
  },
];

export const lessons: Record<string, Lesson[]> = {
  banjar: [
    {
      id: 'banjar-1',
      languageId: 'banjar',
      title: 'Sapaan & Perkenalan',
      description: 'Belajar cara menyapa dan memperkenalkan diri dalam Bahasa Banjar',
      order: 1,
      videoUrl: 'https://example.com/video1',
      thumbnailUrl: '/images/lessons/banjar-1.jpg',
      duration: '8 menit',
      expReward: 100,
      completed: false,
      vocabulary: [
        {
          id: 'v1',
          word: 'Halo',
          translation: 'Halo',
          pronunciation: 'ha-lo',
          example: 'Halo, siapa ngaran ikam?',
          exampleTranslation: 'Halo, siapa nama kamu?',
        },
        {
          id: 'v2',
          word: 'Ngaran',
          translation: 'Nama',
          pronunciation: 'nga-ran',
          example: 'Ngaran ulun Ahmad',
          exampleTranslation: 'Nama saya Ahmad',
        },
        {
          id: 'v3',
          word: 'Ulun',
          translation: 'Saya',
          pronunciation: 'u-lun',
          example: 'Ulun urang Banjar',
          exampleTranslation: 'Saya orang Banjar',
        },
        {
          id: 'v4',
          word: 'Ikam',
          translation: 'Kamu',
          pronunciation: 'i-kam',
          example: 'Ikam dari mana?',
          exampleTranslation: 'Kamu dari mana?',
        },
        {
          id: 'v5',
          word: 'Salamat',
          translation: 'Selamat',
          pronunciation: 'sa-la-mat',
          example: 'Salamat datang!',
          exampleTranslation: 'Selamat datang!',
        },
      ],
      exercises: [
        {
          id: 'e1',
          type: 'multiple-choice',
          question: 'Apa arti kata "Ulun" dalam Bahasa Indonesia?',
          options: ['Kamu', 'Saya', 'Mereka', 'Dia'],
          correctAnswer: 'Saya',
          explanation: '"Ulun" adalah kata ganti orang pertama tunggal dalam Bahasa Banjar, artinya "Saya".',
        },
        {
          id: 'e2',
          type: 'multiple-choice',
          question: 'Bagaimana cara menanyakan nama seseorang dalam Bahasa Banjar?',
          options: ['Siapa ngaran ikam?', 'Apa kabar ikam?', 'Ikam siapa?', 'Ngaran apa?'],
          correctAnswer: 'Siapa ngaran ikam?',
          explanation: '"Siapa ngaran ikam?" adalah cara formal menanyakan nama dalam Bahasa Banjar.',
        },
        {
          id: 'e3',
          type: 'multiple-choice',
          question: 'Lengkapi kalimat berikut: "_____ ulun Ahmad" (Perkenalkan)',
          options: ['Ngaran', 'Siapa', 'Ikam', 'Ulun'],
          correctAnswer: 'Ngaran',
          explanation: '"Ngaran ulun Ahmad" berarti "Nama saya Ahmad".',
        },
      ],
    },
    {
      id: 'banjar-2',
      languageId: 'banjar',
      title: 'Percakapan di Pasar',
      description: 'Pelajari kosakata dan frasa untuk berbelanja di pasar tradisional',
      order: 2,
      videoUrl: 'https://example.com/video2',
      thumbnailUrl: '/images/lessons/banjar-2.jpg',
      duration: '10 menit',
      expReward: 100,
      completed: false,
      vocabulary: [
        {
          id: 'v6',
          word: 'Barapa',
          translation: 'Berapa',
          pronunciation: 'ba-ra-pa',
          example: 'Barapa haraganya?',
          exampleTranslation: 'Berapa harganya?',
        },
        {
          id: 'v7',
          word: 'Mahal',
          translation: 'Mahal',
          pronunciation: 'ma-hal',
          example: 'Mahal banar!',
          exampleTranslation: 'Mahal sekali!',
        },
        {
          id: 'v8',
          word: 'Murah',
          translation: 'Murah',
          pronunciation: 'mu-rah',
          example: 'Ada nang murah?',
          exampleTranslation: 'Ada yang murah?',
        },
        {
          id: 'v9',
          word: 'Kurang',
          translation: 'Kurang',
          pronunciation: 'ku-rang',
          example: 'Kurangi lagi dong',
          exampleTranslation: 'Kurangi lagi dong',
        },
      ],
      exercises: [
        {
          id: 'e4',
          type: 'multiple-choice',
          question: 'Bagaimana cara bertanya harga dalam Bahasa Banjar?',
          options: ['Barapa haraganya?', 'Apa harganya?', 'Mana harganya?', 'Siapa harganya?'],
          correctAnswer: 'Barapa haraganya?',
        },
        {
          id: 'e5',
          type: 'multiple-choice',
          question: 'Pilih padanan yang tepat untuk "Mahal sekali!"',
          options: ['Mahal banar!', 'Murah banar!', 'Bagus banar!', 'Jauh banar!'],
          correctAnswer: 'Mahal banar!',
          explanation: '"Banar" berarti "sekali/sangat" dalam Bahasa Banjar.',
        },
      ],
    },
    {
      id: 'banjar-3',
      languageId: 'banjar',
      title: 'Menanyakan Arah',
      description: 'Cara bertanya dan memberikan petunjuk arah dalam Bahasa Banjar',
      order: 3,
      videoUrl: 'https://example.com/video3',
      thumbnailUrl: '/images/lessons/banjar-3.jpg',
      duration: '9 menit',
      expReward: 100,
      completed: false,
      vocabulary: [
        {
          id: 'v10',
          word: 'Dimana',
          translation: 'Di mana',
          pronunciation: 'di-ma-na',
          example: 'Dimana pasar?',
          exampleTranslation: 'Di mana pasar?',
        },
        {
          id: 'v11',
          word: 'Kanan',
          translation: 'Kanan',
          pronunciation: 'ka-nan',
          example: 'Balok ka kanan',
          exampleTranslation: 'Belok ke kanan',
        },
        {
          id: 'v12',
          word: 'Kiwa',
          translation: 'Kiri',
          pronunciation: 'ki-wa',
          example: 'Balok ka kiwa',
          exampleTranslation: 'Belok ke kiri',
        },
      ],
      exercises: [
        {
          id: 'e6',
          type: 'multiple-choice',
          question: 'Apa arti "Kiwa" dalam Bahasa Indonesia?',
          options: ['Kanan', 'Kiri', 'Lurus', 'Belakang'],
          correctAnswer: 'Kiri',
        },
      ],
    },
    {
      id: 'banjar-4',
      languageId: 'banjar',
      title: 'Makanan & Minuman',
      description: 'Kosakata makanan khas Banjar dan cara memesannya',
      order: 4,
      videoUrl: 'https://example.com/video4',
      thumbnailUrl: '/images/lessons/banjar-4.jpg',
      duration: '12 menit',
      expReward: 100,
      completed: false,
      vocabulary: [
        {
          id: 'v13',
          word: 'Lapar',
          translation: 'Lapar',
          pronunciation: 'la-par',
          example: 'Ulun lapar banar',
          exampleTranslation: 'Saya sangat lapar',
        },
        {
          id: 'v14',
          word: 'Haus',
          translation: 'Haus',
          pronunciation: 'ha-us',
          example: 'Ikam haus kah?',
          exampleTranslation: 'Kamu haus?',
        },
        {
          id: 'v15',
          word: 'Soto Banjar',
          translation: 'Soto khas Banjar',
          pronunciation: 'so-to ban-jar',
          example: 'Ulun handak soto Banjar',
          exampleTranslation: 'Saya mau soto Banjar',
        },
      ],
      exercises: [
        {
          id: 'e7',
          type: 'multiple-choice',
          question: 'Bagaimana mengatakan "Saya sangat lapar" dalam Bahasa Banjar?',
          options: ['Ulun lapar banar', 'Ikam lapar banar', 'Ulun haus banar', 'Sidin lapar banar'],
          correctAnswer: 'Ulun lapar banar',
        },
      ],
    },
  ],
  ambon: [
    {
      id: 'ambon-1',
      languageId: 'ambon',
      title: 'Sapaan Dasar',
      description: 'Belajar sapaan dan ungkapan dasar dalam Bahasa Ambon',
      order: 1,
      videoUrl: 'https://example.com/video-ambon1',
      thumbnailUrl: '/images/lessons/ambon-1.jpg',
      duration: '7 menit',
      expReward: 100,
      completed: false,
      vocabulary: [
        {
          id: 'va1',
          word: 'Beta',
          translation: 'Saya',
          pronunciation: 'be-ta',
          example: 'Beta su makan',
          exampleTranslation: 'Saya sudah makan',
        },
        {
          id: 'va2',
          word: 'Ose',
          translation: 'Kamu',
          pronunciation: 'o-se',
          example: 'Ose mau kemana?',
          exampleTranslation: 'Kamu mau ke mana?',
        },
        {
          id: 'va3',
          word: 'Ale',
          translation: 'Kalian',
          pronunciation: 'a-le',
          example: 'Ale datang dari mana?',
          exampleTranslation: 'Kalian datang dari mana?',
        },
        {
          id: 'va4',
          word: 'Seng',
          translation: 'Tidak',
          pronunciation: 'seng',
          example: 'Beta seng tau',
          exampleTranslation: 'Saya tidak tahu',
        },
        {
          id: 'va5',
          word: 'Su',
          translation: 'Sudah',
          pronunciation: 'su',
          example: 'Ose su makan?',
          exampleTranslation: 'Kamu sudah makan?',
        },
      ],
      exercises: [
        {
          id: 'ea1',
          type: 'multiple-choice',
          question: 'Apa arti kata "Beta" dalam Bahasa Indonesia?',
          options: ['Kamu', 'Saya', 'Mereka', 'Dia'],
          correctAnswer: 'Saya',
          explanation: '"Beta" adalah kata ganti orang pertama tunggal dalam Bahasa Ambon.',
        },
        {
          id: 'ea2',
          type: 'multiple-choice',
          question: 'Bagaimana mengatakan "Saya tidak tahu" dalam Bahasa Ambon?',
          options: ['Beta seng tau', 'Beta su tau', 'Ose seng tau', 'Ale seng tau'],
          correctAnswer: 'Beta seng tau',
        },
      ],
    },
    {
      id: 'ambon-2',
      languageId: 'ambon',
      title: 'Ekspresi Sehari-hari',
      description: 'Ungkapan yang sering digunakan dalam percakapan sehari-hari',
      order: 2,
      videoUrl: 'https://example.com/video-ambon2',
      thumbnailUrl: '/images/lessons/ambon-2.jpg',
      duration: '9 menit',
      expReward: 100,
      completed: false,
      vocabulary: [
        {
          id: 'va6',
          word: 'Par',
          translation: 'Untuk/Buat',
          pronunciation: 'par',
          example: 'Ini par ose',
          exampleTranslation: 'Ini untuk kamu',
        },
        {
          id: 'va7',
          word: 'Dolo',
          translation: 'Dulu',
          pronunciation: 'do-lo',
          example: 'Tunggu dolo',
          exampleTranslation: 'Tunggu dulu',
        },
        {
          id: 'va8',
          word: 'Bae-bae',
          translation: 'Baik-baik',
          pronunciation: 'bae-bae',
          example: 'Jalan bae-bae',
          exampleTranslation: 'Jalan baik-baik',
        },
      ],
      exercises: [
        {
          id: 'ea3',
          type: 'multiple-choice',
          question: 'Bagaimana mengatakan "Tunggu dulu" dalam Bahasa Ambon?',
          options: ['Tunggu dolo', 'Tunggu su', 'Tunggu par', 'Tunggu bae'],
          correctAnswer: 'Tunggu dolo',
        },
      ],
    },
    {
      id: 'ambon-3',
      languageId: 'ambon',
      title: 'Di Warung Makan',
      description: 'Percakapan dan kosakata untuk memesan makanan',
      order: 3,
      videoUrl: 'https://example.com/video-ambon3',
      thumbnailUrl: '/images/lessons/ambon-3.jpg',
      duration: '10 menit',
      expReward: 100,
      completed: false,
      vocabulary: [
        {
          id: 'va9',
          word: 'Makan',
          translation: 'Makan',
          pronunciation: 'ma-kan',
          example: 'Beta mau makan',
          exampleTranslation: 'Saya mau makan',
        },
        {
          id: 'va10',
          word: 'Ikan',
          translation: 'Ikan',
          pronunciation: 'i-kan',
          example: 'Ada ikan bakar?',
          exampleTranslation: 'Ada ikan bakar?',
        },
        {
          id: 'va11',
          word: 'Peda',
          translation: 'Pedas',
          pronunciation: 'pe-da',
          example: 'Jang terlalu peda',
          exampleTranslation: 'Jangan terlalu pedas',
        },
      ],
      exercises: [
        {
          id: 'ea4',
          type: 'multiple-choice',
          question: 'Apa arti "Peda" dalam Bahasa Indonesia?',
          options: ['Manis', 'Asin', 'Pedas', 'Asam'],
          correctAnswer: 'Pedas',
        },
      ],
    },
  ],
};

export const vouchers: Voucher[] = [
  {
    id: 'voucher-1',
    name: 'Diskon 50% Kelas Mentoring',
    description: 'Voucher diskon 50% untuk sesi mentoring 1-on-1 dengan native speaker',
    imageUrl: '/images/vouchers/mentoring.png',
    tokenCost: 100,
    redeemed: false,
  },
  {
    id: 'voucher-2',
    name: 'Merchandise Kasturi',
    description: 'Kaos eksklusif Kasturi dengan desain bahasa daerah',
    imageUrl: '/images/vouchers/merch.png',
    tokenCost: 200,
    redeemed: false,
  },
  {
    id: 'voucher-3',
    name: 'Akses Premium 1 Bulan',
    description: 'Akses ke semua konten premium selama 1 bulan',
    imageUrl: '/images/vouchers/premium.png',
    tokenCost: 150,
    redeemed: false,
  },
  {
    id: 'voucher-4',
    name: 'E-Book Budaya Nusantara',
    description: 'Koleksi e-book tentang budaya dan bahasa daerah Indonesia',
    imageUrl: '/images/vouchers/ebook.png',
    tokenCost: 50,
    redeemed: false,
  },
];

export const exchangeRate: ExchangeRate = {
  expToToken: 10,
  tokenToVoucher: {
    'voucher-1': 100,
    'voucher-2': 200,
    'voucher-3': 150,
    'voucher-4': 50,
  },
};

export const testimonials = [
  {
    id: 1,
    name: 'Andi Pratama',
    role: 'Mahasiswa di Banjarmasin',
    avatar: '/images/avatars/andi.jpg',
    content: 'Kasturi membantu saya cepat beradaptasi saat kuliah di Banjarmasin. Sekarang saya bisa ngobrol lancar dengan teman-teman lokal!',
    rating: 5,
  },
  {
    id: 2,
    name: 'Siti Rahayu',
    role: 'Pekerja di Ambon',
    avatar: '/images/avatars/siti.jpg',
    content: 'Belajar Bahasa Ambon jadi menyenangkan. Modul-modulnya praktis dan langsung bisa dipraktekkan.',
    rating: 5,
  },
  {
    id: 3,
    name: 'Budi Santoso',
    role: 'Pengusaha',
    avatar: '/images/avatars/budi.jpg',
    content: 'Sertifikat dari Kasturi membuktikan keseriusan saya belajar bahasa daerah. Partner bisnis lokal jadi lebih percaya.',
    rating: 5,
  },
];

export const features = [
  {
    icon: 'BookOpen',
    title: 'Pembelajaran Terstruktur',
    description: 'Modul-modul yang disusun sistematis dari dasar hingga mahir, dengan fokus pada percakapan sehari-hari.',
  },
  {
    icon: 'Video',
    title: 'Video Interaktif',
    description: 'Belajar dari native speaker melalui video percakapan real-life yang mudah dipahami.',
  },
  {
    icon: 'Award',
    title: 'Sertifikat Terverifikasi',
    description: 'Dapatkan credential on-chain yang dapat diverifikasi siapapun sebagai bukti pembelajaran.',
  },
  {
    icon: 'Gift',
    title: 'Reward & Voucher',
    description: 'Kumpulkan EXP, tukarkan ke token, dan dapatkan voucher eksklusif untuk mentoring atau merchandise.',
  },
  {
    icon: 'Users',
    title: 'Komunitas Learner',
    description: 'Bergabung dengan komunitas pelajar bahasa daerah dari seluruh Indonesia.',
  },
  {
    icon: 'Shield',
    title: 'Privasi Terjaga',
    description: 'Login mudah dengan email atau social media. Blockchain bekerja di balik layar.',
  },
];
